# Generated by Django 4.0.2 on 2022-02-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_dr', models.CharField(max_length=200)),
                ('state_dr', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
            ],
        ),
    ]
