# Generated by Django 4.0.2 on 2022-02-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induz', '0002_register_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_tb',
            name='password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
