# Generated by Django 4.0.2 on 2022-03-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induz', '0004_img_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_tb',
            name='picture',
            field=models.ImageField(default=1, upload_to='picture'),
            preserve_default=False,
        ),
    ]
