# Generated by Django 4.0.2 on 2022-03-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('induz', '0005_img_tb_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='fav_steel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_steel_u', models.CharField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='induz.first_tb')),
            ],
        ),
    ]
